#!/bin/bash
mkdir -p ssl-fallback
openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 \
    -subj '/CN=sni-support-required-for-valid-ssl' \
    -keyout ssl-fallback/resty-auto-ssl-fallback.key \
    -out ssl-fallback/resty-auto-ssl-fallback.crt